org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# to use CI Server location.
# org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
# org.gradle.user.home=/Volumes/JINSSD/Users/Spezzato/Library/Android/sdk
#C\:\\Program Files\\Java\\jdk-17
#/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
org.gradle.parallel=false
